# Generated by Django 5.0.8 on 2024-12-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="project_role",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("project_admin", "Admin"),
                    ("project_developer", "Project Developer"),
                    ("consultant", "Consultant"),
                    ("regulator", "Regulator"),
                    ("public_stakeholder", "Public Stakeholder"),
                    ("independent_expert", "Independent Expert"),
                ],
                max_length=50,
            ),
        ),
    ]
