# Generated by Django 5.0.8 on 2025-01-02 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="user_management.company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_admin",
            field=models.ForeignKey(
                help_text="The project admin responsible for managing this project.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_administrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectuserrole",
            name="project",
            field=models.ForeignKey(
                help_text="The project associated with this role.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_roles",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="projectuserrole",
            name="user",
            field=models.ForeignKey(
                help_text="The user assigned to this role.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectuserrolerequest",
            name="project",
            field=models.ForeignKey(
                help_text="The project the user wants to join.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_requests",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="projectuserrolerequest",
            name="user",
            field=models.ForeignKey(
                help_text="The user requesting to join the project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuserrole",
            unique_together={("user", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="projectuserrolerequest",
            unique_together={("user", "project", "project_role")},
        ),
    ]
