# Generated by Django 5.0.8 on 2024-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screening",
            options={
                "ordering": ["-date_screened"],
                "verbose_name": "Screening",
                "verbose_name_plural": "Screenings--",
            },
        ),
        migrations.RenameField(
            model_name="screening",
            old_name="created_at",
            new_name="date_screened",
        ),
        migrations.RemoveField(
            model_name="screening",
            name="screening_result",
        ),
        migrations.RemoveField(
            model_name="screening",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="screening",
            name="air_quality_impact",
            field=models.CharField(
                default="minimal",
                help_text="Describe the impact on air quality (e.g., minimal, significant).",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="area_covered",
            field=models.FloatField(
                default="20",
                help_text="The total area covered by the project in hectares.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="biodiversity_impacts",
            field=models.BooleanField(
                default=False,
                help_text="Specify if the project has potential biodiversity impacts.",
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="community_support",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if there is community support for the project.",
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="construction_duration",
            field=models.IntegerField(
                default="2",
                help_text="Duration of the construction phase in months.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="expected_output",
            field=models.FloatField(
                default=50,
                help_text="Expected output of the project (e.g., in MW for energy projects).",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="flora_fauna_impact",
            field=models.CharField(
                default="low risk to endangered species",
                help_text="Describe the impact on flora and fauna.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="infrastructure",
            field=models.JSONField(
                default=["turbines", "access roads", "substations"],
                help_text="List of infrastructure involved, such as turbines, access roads, etc.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="mitigation_measures_required",
            field=models.BooleanField(
                default=False, help_text="Indicate if mitigation measures are required."
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="next_steps",
            field=models.CharField(
                blank=True,
                help_text="Next steps in the EIA process.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="noise_impact",
            field=models.CharField(
                default="moderate during construction",
                help_text="Describe the noise impact during construction and operation.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="operational_duration",
            field=models.IntegerField(
                default="30", help_text="Duration of the operational phase in years."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="protected_areas",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if the project affects any protected areas.",
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="public_opposition",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if there is public opposition to the project.",
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="reason_for_decision",
            field=models.TextField(
                blank=True,
                help_text="Explanation for the screening decision.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="screening_decision",
            field=models.CharField(
                blank=True,
                help_text="Decision outcome (e.g., EIA required).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="screening_officer",
            field=models.CharField(
                blank=True,
                help_text="Name of the screening officer.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screening",
            name="water_pollution_impact",
            field=models.CharField(
                default="none",
                help_text="Describe the impact on water pollution.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screening",
            name="water_resources_impacts",
            field=models.BooleanField(
                default=False,
                help_text="Specify if the project impacts water resources.",
            ),
        ),
    ]
