# Generated by Django 5.0.8 on 2024-09-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0002_alter_screening_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screening",
            options={
                "ordering": ["-date_screened"],
                "verbose_name": "Screening",
                "verbose_name_plural": "Screenings",
            },
        ),
    ]
