# Generated by Django 5.0.8 on 2024-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0003_alter_screening_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screening",
            name="mitigation_measures_required",
        ),
        migrations.RemoveField(
            model_name="screening",
            name="next_steps",
        ),
        migrations.RemoveField(
            model_name="screening",
            name="reason_for_decision",
        ),
        migrations.RemoveField(
            model_name="screening",
            name="screening_decision",
        ),
        migrations.AddField(
            model_name="screening",
            name="screening_result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
