# Generated by Django 5.0.8 on 2024-09-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0004_remove_screening_mitigation_measures_required_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screening",
            name="screening_officer",
        ),
    ]
