# Generated by Django 5.0.8 on 2024-09-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="screening_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_screening_step",
                to="screening.screening",
            ),
        ),
    ]
