# Generated by Django 5.0.8 on 2024-09-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_project_screening_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
