# Generated by Django 5.0.8 on 2024-11-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_project_additional_links_project_budget_estimate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="spent_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
